// Maps Bzzoiro nationality strings to ISO 3166-1 alpha-2 codes
// Use flagcdn.com for actual flag images: https://flagcdn.com/w40/{code}.png

const COUNTRY_TO_ISO: Record<string, string> = {
  // South America
  Argentina: 'ar',
  Brazil: 'br',
  Uruguay: 'uy',
  Colombia: 'co',
  Chile: 'cl',
  Peru: 'pe',
  Ecuador: 'ec',
  Venezuela: 've',
  Paraguay: 'py',
  Bolivia: 'bo',
  // Europe
  England: 'gb-eng',
  Scotland: 'gb-sct',
  Wales: 'gb-wls',
  'Northern Ireland': 'gb-nir',
  Spain: 'es',
  Italy: 'it',
  Germany: 'de',
  France: 'fr',
  Portugal: 'pt',
  Netherlands: 'nl',
  Belgium: 'be',
  Croatia: 'hr',
  Serbia: 'rs',
  Poland: 'pl',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Slovakia: 'sk',
  Slovenia: 'si',
  Austria: 'at',
  Switzerland: 'ch',
  Sweden: 'se',
  Norway: 'no',
  Denmark: 'dk',
  Finland: 'fi',
  Iceland: 'is',
  Ireland: 'ie',
  'Republic of Ireland': 'ie',
  Russia: 'ru',
  Ukraine: 'ua',
  Turkey: 'tr',
  Greece: 'gr',
  Bulgaria: 'bg',
  Romania: 'ro',
  Hungary: 'hu',
  Albania: 'al',
  'Bosnia and Herzegovina': 'ba',
  'North Macedonia': 'mk',
  Montenegro: 'me',
  Kosovo: 'xk',
  // Africa
  Egypt: 'eg',
  Senegal: 'sn',
  Mali: 'ml',
  'Ivory Coast': 'ci',
  "Côte d'Ivoire": 'ci',
  Nigeria: 'ng',
  Cameroon: 'cm',
  Morocco: 'ma',
  Algeria: 'dz',
  Tunisia: 'tn',
  Ghana: 'gh',
  'South Africa': 'za',
  'DR Congo': 'cd',
  Congo: 'cg',
  'Burkina Faso': 'bf',
  Gabon: 'ga',
  'Equatorial Guinea': 'gq',
  Comoros: 'km',
  'Cape Verde': 'cv',
  Guinea: 'gn',
  'Guinea-Bissau': 'gw',
  'Sierra Leone': 'sl',
  Liberia: 'lr',
  Mauritania: 'mr',
  Sudan: 'sd',
  Ethiopia: 'et',
  Kenya: 'ke',
  Uganda: 'ug',
  Tanzania: 'tz',
  Zimbabwe: 'zw',
  Zambia: 'zm',
  Angola: 'ao',
  Mozambique: 'mz',
  Madagascar: 'mg',
  // North America
  Mexico: 'mx',
  USA: 'us',
  'United States': 'us',
  Canada: 'ca',
  'Costa Rica': 'cr',
  Panama: 'pa',
  Honduras: 'hn',
  Guatemala: 'gt',
  'El Salvador': 'sv',
  Jamaica: 'jm',
  'Trinidad and Tobago': 'tt',
  Cuba: 'cu',
  'Dominican Republic': 'do',
  Haiti: 'ht',
  // Asia
  Japan: 'jp',
  'South Korea': 'kr',
  China: 'cn',
  'Saudi Arabia': 'sa',
  Iran: 'ir',
  Iraq: 'iq',
  Qatar: 'qa',
  UAE: 'ae',
  'United Arab Emirates': 'ae',
  Bahrain: 'bh',
  Kuwait: 'kw',
  Oman: 'om',
  Lebanon: 'lb',
  Syria: 'sy',
  Jordan: 'jo',
  Israel: 'il',
  Palestine: 'ps',
  Thailand: 'th',
  Vietnam: 'vn',
  Indonesia: 'id',
  Malaysia: 'my',
  Philippines: 'ph',
  Singapore: 'sg',
  India: 'in',
  // Oceania
  Australia: 'au',
  'New Zealand': 'nz',
};

export function nationalityToFlagUrl(nationality: string | null | undefined, w: number = 40): string | null {
  if (!nationality) return null;
  const code = COUNTRY_TO_ISO[nationality];
  if (!code) return null;
  return `https://flagcdn.com/w${w}/${code}.png`;
}
